version: '3'

services:
  apimealuga:
    build: ./API
    ports:
      - "50:80"
    networks:
      - RedeTop    

  appmealuga:
    build: ./APP
    ports:
      - "51:8080"
    networks:
    - RedeTop
    depends_on:
      - "apimealuga"

networks: 
    RedeTop:
        driver: bridge
