version: '3'

services:
  API:
    build: ./API
    ports:
      - "50:80"
    networks:
      - RedeTop    

  APP:
    build: ./APP
    ports:
      - "51:8080"
    networks:
    - RedeTop
    depends_on:
      - "API"

networks: 
    RedeTop:
        driver: bridge
